services:
  api:
    build:
      context: .
      dockerfile: VolvoCarHealth.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=VolvoCarHealthDb;User=sa;Password=volvo@2025;TrustServerCertificate=True;

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "volvo@2025"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
